opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping

disabled_rules:
  - trailing_whitespace
  - line_length

excluded:
  - Tuist
  - Derived
  - Project.swift
  - vendor
  - vendor/bundle
  - Pods
  - Carthage
  - .build
  - DerivedData

type_body_length:
  warning: 300
  error: 500
